// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteV1OrgsOrgIDParams creates a new DeleteV1OrgsOrgIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteV1OrgsOrgIDParams() *DeleteV1OrgsOrgIDParams {
	return &DeleteV1OrgsOrgIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteV1OrgsOrgIDParamsWithTimeout creates a new DeleteV1OrgsOrgIDParams object
// with the ability to set a timeout on a request.
func NewDeleteV1OrgsOrgIDParamsWithTimeout(timeout time.Duration) *DeleteV1OrgsOrgIDParams {
	return &DeleteV1OrgsOrgIDParams{
		timeout: timeout,
	}
}

// NewDeleteV1OrgsOrgIDParamsWithContext creates a new DeleteV1OrgsOrgIDParams object
// with the ability to set a context for a request.
func NewDeleteV1OrgsOrgIDParamsWithContext(ctx context.Context) *DeleteV1OrgsOrgIDParams {
	return &DeleteV1OrgsOrgIDParams{
		Context: ctx,
	}
}

// NewDeleteV1OrgsOrgIDParamsWithHTTPClient creates a new DeleteV1OrgsOrgIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteV1OrgsOrgIDParamsWithHTTPClient(client *http.Client) *DeleteV1OrgsOrgIDParams {
	return &DeleteV1OrgsOrgIDParams{
		HTTPClient: client,
	}
}

/*
DeleteV1OrgsOrgIDParams contains all the parameters to send to the API endpoint

	for the delete v1 orgs org ID operation.

	Typically these are written to a http.Request.
*/
type DeleteV1OrgsOrgIDParams struct {

	/* OrgID.

	   org ID for your current org
	*/
	OrgID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete v1 orgs org ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteV1OrgsOrgIDParams) WithDefaults() *DeleteV1OrgsOrgIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete v1 orgs org ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteV1OrgsOrgIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete v1 orgs org ID params
func (o *DeleteV1OrgsOrgIDParams) WithTimeout(timeout time.Duration) *DeleteV1OrgsOrgIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete v1 orgs org ID params
func (o *DeleteV1OrgsOrgIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete v1 orgs org ID params
func (o *DeleteV1OrgsOrgIDParams) WithContext(ctx context.Context) *DeleteV1OrgsOrgIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete v1 orgs org ID params
func (o *DeleteV1OrgsOrgIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete v1 orgs org ID params
func (o *DeleteV1OrgsOrgIDParams) WithHTTPClient(client *http.Client) *DeleteV1OrgsOrgIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete v1 orgs org ID params
func (o *DeleteV1OrgsOrgIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgID adds the orgID to the delete v1 orgs org ID params
func (o *DeleteV1OrgsOrgIDParams) WithOrgID(orgID string) *DeleteV1OrgsOrgIDParams {
	o.SetOrgID(orgID)
	return o
}

// SetOrgID adds the orgId to the delete v1 orgs org ID params
func (o *DeleteV1OrgsOrgIDParams) SetOrgID(orgID string) {
	o.OrgID = orgID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteV1OrgsOrgIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param org_id
	if err := r.SetPathParam("org_id", o.OrgID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
