// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteV1OrgsOrgIDReader is a Reader for the DeleteV1OrgsOrgID structure.
type DeleteV1OrgsOrgIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1OrgsOrgIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDeleteV1OrgsOrgIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/orgs/{org_id}] DeleteV1OrgsOrgID", response, response.Code())
	}
}

// NewDeleteV1OrgsOrgIDCreated creates a DeleteV1OrgsOrgIDCreated with default headers values
func NewDeleteV1OrgsOrgIDCreated() *DeleteV1OrgsOrgIDCreated {
	return &DeleteV1OrgsOrgIDCreated{}
}

/*
DeleteV1OrgsOrgIDCreated describes a response with status code 201, with default header values.

Created
*/
type DeleteV1OrgsOrgIDCreated struct {
	Payload string
}

// IsSuccess returns true when this delete v1 orgs org Id created response has a 2xx status code
func (o *DeleteV1OrgsOrgIDCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete v1 orgs org Id created response has a 3xx status code
func (o *DeleteV1OrgsOrgIDCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 orgs org Id created response has a 4xx status code
func (o *DeleteV1OrgsOrgIDCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v1 orgs org Id created response has a 5xx status code
func (o *DeleteV1OrgsOrgIDCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 orgs org Id created response a status code equal to that given
func (o *DeleteV1OrgsOrgIDCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the delete v1 orgs org Id created response
func (o *DeleteV1OrgsOrgIDCreated) Code() int {
	return 201
}

func (o *DeleteV1OrgsOrgIDCreated) Error() string {
	return fmt.Sprintf("[DELETE /v1/orgs/{org_id}][%d] deleteV1OrgsOrgIdCreated  %+v", 201, o.Payload)
}

func (o *DeleteV1OrgsOrgIDCreated) String() string {
	return fmt.Sprintf("[DELETE /v1/orgs/{org_id}][%d] deleteV1OrgsOrgIdCreated  %+v", 201, o.Payload)
}

func (o *DeleteV1OrgsOrgIDCreated) GetPayload() string {
	return o.Payload
}

func (o *DeleteV1OrgsOrgIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
