// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1ComponentsComponentIDConfigParams creates a new GetV1ComponentsComponentIDConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1ComponentsComponentIDConfigParams() *GetV1ComponentsComponentIDConfigParams {
	return &GetV1ComponentsComponentIDConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1ComponentsComponentIDConfigParamsWithTimeout creates a new GetV1ComponentsComponentIDConfigParams object
// with the ability to set a timeout on a request.
func NewGetV1ComponentsComponentIDConfigParamsWithTimeout(timeout time.Duration) *GetV1ComponentsComponentIDConfigParams {
	return &GetV1ComponentsComponentIDConfigParams{
		timeout: timeout,
	}
}

// NewGetV1ComponentsComponentIDConfigParamsWithContext creates a new GetV1ComponentsComponentIDConfigParams object
// with the ability to set a context for a request.
func NewGetV1ComponentsComponentIDConfigParamsWithContext(ctx context.Context) *GetV1ComponentsComponentIDConfigParams {
	return &GetV1ComponentsComponentIDConfigParams{
		Context: ctx,
	}
}

// NewGetV1ComponentsComponentIDConfigParamsWithHTTPClient creates a new GetV1ComponentsComponentIDConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1ComponentsComponentIDConfigParamsWithHTTPClient(client *http.Client) *GetV1ComponentsComponentIDConfigParams {
	return &GetV1ComponentsComponentIDConfigParams{
		HTTPClient: client,
	}
}

/*
GetV1ComponentsComponentIDConfigParams contains all the parameters to send to the API endpoint

	for the get v1 components component ID config operation.

	Typically these are written to a http.Request.
*/
type GetV1ComponentsComponentIDConfigParams struct {

	/* ComponentID.

	   component ID
	*/
	ComponentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 components component ID config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ComponentsComponentIDConfigParams) WithDefaults() *GetV1ComponentsComponentIDConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 components component ID config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ComponentsComponentIDConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 components component ID config params
func (o *GetV1ComponentsComponentIDConfigParams) WithTimeout(timeout time.Duration) *GetV1ComponentsComponentIDConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 components component ID config params
func (o *GetV1ComponentsComponentIDConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 components component ID config params
func (o *GetV1ComponentsComponentIDConfigParams) WithContext(ctx context.Context) *GetV1ComponentsComponentIDConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 components component ID config params
func (o *GetV1ComponentsComponentIDConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 components component ID config params
func (o *GetV1ComponentsComponentIDConfigParams) WithHTTPClient(client *http.Client) *GetV1ComponentsComponentIDConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 components component ID config params
func (o *GetV1ComponentsComponentIDConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithComponentID adds the componentID to the get v1 components component ID config params
func (o *GetV1ComponentsComponentIDConfigParams) WithComponentID(componentID string) *GetV1ComponentsComponentIDConfigParams {
	o.SetComponentID(componentID)
	return o
}

// SetComponentID adds the componentId to the get v1 components component ID config params
func (o *GetV1ComponentsComponentIDConfigParams) SetComponentID(componentID string) {
	o.ComponentID = componentID
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1ComponentsComponentIDConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param component_id
	if err := r.SetPathParam("component_id", o.ComponentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
