// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1ComponentsComponentIDBuildBuildIDParams creates a new GetV1ComponentsComponentIDBuildBuildIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1ComponentsComponentIDBuildBuildIDParams() *GetV1ComponentsComponentIDBuildBuildIDParams {
	return &GetV1ComponentsComponentIDBuildBuildIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1ComponentsComponentIDBuildBuildIDParamsWithTimeout creates a new GetV1ComponentsComponentIDBuildBuildIDParams object
// with the ability to set a timeout on a request.
func NewGetV1ComponentsComponentIDBuildBuildIDParamsWithTimeout(timeout time.Duration) *GetV1ComponentsComponentIDBuildBuildIDParams {
	return &GetV1ComponentsComponentIDBuildBuildIDParams{
		timeout: timeout,
	}
}

// NewGetV1ComponentsComponentIDBuildBuildIDParamsWithContext creates a new GetV1ComponentsComponentIDBuildBuildIDParams object
// with the ability to set a context for a request.
func NewGetV1ComponentsComponentIDBuildBuildIDParamsWithContext(ctx context.Context) *GetV1ComponentsComponentIDBuildBuildIDParams {
	return &GetV1ComponentsComponentIDBuildBuildIDParams{
		Context: ctx,
	}
}

// NewGetV1ComponentsComponentIDBuildBuildIDParamsWithHTTPClient creates a new GetV1ComponentsComponentIDBuildBuildIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1ComponentsComponentIDBuildBuildIDParamsWithHTTPClient(client *http.Client) *GetV1ComponentsComponentIDBuildBuildIDParams {
	return &GetV1ComponentsComponentIDBuildBuildIDParams{
		HTTPClient: client,
	}
}

/*
GetV1ComponentsComponentIDBuildBuildIDParams contains all the parameters to send to the API endpoint

	for the get v1 components component ID build build ID operation.

	Typically these are written to a http.Request.
*/
type GetV1ComponentsComponentIDBuildBuildIDParams struct {

	/* BuildID.

	   build ID
	*/
	BuildID string

	/* ComponentID.

	   component ID
	*/
	ComponentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 components component ID build build ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ComponentsComponentIDBuildBuildIDParams) WithDefaults() *GetV1ComponentsComponentIDBuildBuildIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 components component ID build build ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ComponentsComponentIDBuildBuildIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 components component ID build build ID params
func (o *GetV1ComponentsComponentIDBuildBuildIDParams) WithTimeout(timeout time.Duration) *GetV1ComponentsComponentIDBuildBuildIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 components component ID build build ID params
func (o *GetV1ComponentsComponentIDBuildBuildIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 components component ID build build ID params
func (o *GetV1ComponentsComponentIDBuildBuildIDParams) WithContext(ctx context.Context) *GetV1ComponentsComponentIDBuildBuildIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 components component ID build build ID params
func (o *GetV1ComponentsComponentIDBuildBuildIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 components component ID build build ID params
func (o *GetV1ComponentsComponentIDBuildBuildIDParams) WithHTTPClient(client *http.Client) *GetV1ComponentsComponentIDBuildBuildIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 components component ID build build ID params
func (o *GetV1ComponentsComponentIDBuildBuildIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBuildID adds the buildID to the get v1 components component ID build build ID params
func (o *GetV1ComponentsComponentIDBuildBuildIDParams) WithBuildID(buildID string) *GetV1ComponentsComponentIDBuildBuildIDParams {
	o.SetBuildID(buildID)
	return o
}

// SetBuildID adds the buildId to the get v1 components component ID build build ID params
func (o *GetV1ComponentsComponentIDBuildBuildIDParams) SetBuildID(buildID string) {
	o.BuildID = buildID
}

// WithComponentID adds the componentID to the get v1 components component ID build build ID params
func (o *GetV1ComponentsComponentIDBuildBuildIDParams) WithComponentID(componentID string) *GetV1ComponentsComponentIDBuildBuildIDParams {
	o.SetComponentID(componentID)
	return o
}

// SetComponentID adds the componentId to the get v1 components component ID build build ID params
func (o *GetV1ComponentsComponentIDBuildBuildIDParams) SetComponentID(componentID string) {
	o.ComponentID = componentID
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1ComponentsComponentIDBuildBuildIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param build_id
	if err := r.SetPathParam("build_id", o.BuildID); err != nil {
		return err
	}

	// path param component_id
	if err := r.SetPathParam("component_id", o.ComponentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
