// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/terraform-provider-nuon/internal/api/client/models"
)

// GetV1ComponentsComponentIDBuildBuildIDReader is a Reader for the GetV1ComponentsComponentIDBuildBuildID structure.
type GetV1ComponentsComponentIDBuildBuildIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1ComponentsComponentIDBuildBuildIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1ComponentsComponentIDBuildBuildIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/components/{component_id}/build/{build_id}] GetV1ComponentsComponentIDBuildBuildID", response, response.Code())
	}
}

// NewGetV1ComponentsComponentIDBuildBuildIDOK creates a GetV1ComponentsComponentIDBuildBuildIDOK with default headers values
func NewGetV1ComponentsComponentIDBuildBuildIDOK() *GetV1ComponentsComponentIDBuildBuildIDOK {
	return &GetV1ComponentsComponentIDBuildBuildIDOK{}
}

/*
GetV1ComponentsComponentIDBuildBuildIDOK describes a response with status code 200, with default header values.

OK
*/
type GetV1ComponentsComponentIDBuildBuildIDOK struct {
	Payload *models.AppComponentBuild
}

// IsSuccess returns true when this get v1 components component Id build build Id o k response has a 2xx status code
func (o *GetV1ComponentsComponentIDBuildBuildIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 components component Id build build Id o k response has a 3xx status code
func (o *GetV1ComponentsComponentIDBuildBuildIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 components component Id build build Id o k response has a 4xx status code
func (o *GetV1ComponentsComponentIDBuildBuildIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 components component Id build build Id o k response has a 5xx status code
func (o *GetV1ComponentsComponentIDBuildBuildIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 components component Id build build Id o k response a status code equal to that given
func (o *GetV1ComponentsComponentIDBuildBuildIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 components component Id build build Id o k response
func (o *GetV1ComponentsComponentIDBuildBuildIDOK) Code() int {
	return 200
}

func (o *GetV1ComponentsComponentIDBuildBuildIDOK) Error() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/build/{build_id}][%d] getV1ComponentsComponentIdBuildBuildIdOK  %+v", 200, o.Payload)
}

func (o *GetV1ComponentsComponentIDBuildBuildIDOK) String() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/build/{build_id}][%d] getV1ComponentsComponentIdBuildBuildIdOK  %+v", 200, o.Payload)
}

func (o *GetV1ComponentsComponentIDBuildBuildIDOK) GetPayload() *models.AppComponentBuild {
	return o.Payload
}

func (o *GetV1ComponentsComponentIDBuildBuildIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppComponentBuild)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
