// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1VcsOrgIDConnectedReposParams creates a new GetV1VcsOrgIDConnectedReposParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1VcsOrgIDConnectedReposParams() *GetV1VcsOrgIDConnectedReposParams {
	return &GetV1VcsOrgIDConnectedReposParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1VcsOrgIDConnectedReposParamsWithTimeout creates a new GetV1VcsOrgIDConnectedReposParams object
// with the ability to set a timeout on a request.
func NewGetV1VcsOrgIDConnectedReposParamsWithTimeout(timeout time.Duration) *GetV1VcsOrgIDConnectedReposParams {
	return &GetV1VcsOrgIDConnectedReposParams{
		timeout: timeout,
	}
}

// NewGetV1VcsOrgIDConnectedReposParamsWithContext creates a new GetV1VcsOrgIDConnectedReposParams object
// with the ability to set a context for a request.
func NewGetV1VcsOrgIDConnectedReposParamsWithContext(ctx context.Context) *GetV1VcsOrgIDConnectedReposParams {
	return &GetV1VcsOrgIDConnectedReposParams{
		Context: ctx,
	}
}

// NewGetV1VcsOrgIDConnectedReposParamsWithHTTPClient creates a new GetV1VcsOrgIDConnectedReposParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1VcsOrgIDConnectedReposParamsWithHTTPClient(client *http.Client) *GetV1VcsOrgIDConnectedReposParams {
	return &GetV1VcsOrgIDConnectedReposParams{
		HTTPClient: client,
	}
}

/*
GetV1VcsOrgIDConnectedReposParams contains all the parameters to send to the API endpoint

	for the get v1 vcs org ID connected repos operation.

	Typically these are written to a http.Request.
*/
type GetV1VcsOrgIDConnectedReposParams struct {

	/* OrgID.

	   org ID for your current org
	*/
	OrgID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 vcs org ID connected repos params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1VcsOrgIDConnectedReposParams) WithDefaults() *GetV1VcsOrgIDConnectedReposParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 vcs org ID connected repos params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1VcsOrgIDConnectedReposParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 vcs org ID connected repos params
func (o *GetV1VcsOrgIDConnectedReposParams) WithTimeout(timeout time.Duration) *GetV1VcsOrgIDConnectedReposParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 vcs org ID connected repos params
func (o *GetV1VcsOrgIDConnectedReposParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 vcs org ID connected repos params
func (o *GetV1VcsOrgIDConnectedReposParams) WithContext(ctx context.Context) *GetV1VcsOrgIDConnectedReposParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 vcs org ID connected repos params
func (o *GetV1VcsOrgIDConnectedReposParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 vcs org ID connected repos params
func (o *GetV1VcsOrgIDConnectedReposParams) WithHTTPClient(client *http.Client) *GetV1VcsOrgIDConnectedReposParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 vcs org ID connected repos params
func (o *GetV1VcsOrgIDConnectedReposParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgID adds the orgID to the get v1 vcs org ID connected repos params
func (o *GetV1VcsOrgIDConnectedReposParams) WithOrgID(orgID string) *GetV1VcsOrgIDConnectedReposParams {
	o.SetOrgID(orgID)
	return o
}

// SetOrgID adds the orgId to the get v1 vcs org ID connected repos params
func (o *GetV1VcsOrgIDConnectedReposParams) SetOrgID(orgID string) {
	o.OrgID = orgID
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1VcsOrgIDConnectedReposParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param org_id
	if err := r.SetPathParam("org_id", o.OrgID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
