// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/terraform-provider-nuon/internal/api/client/models"
)

// GetV1VcsOrgIDConnectionsReader is a Reader for the GetV1VcsOrgIDConnections structure.
type GetV1VcsOrgIDConnectionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1VcsOrgIDConnectionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1VcsOrgIDConnectionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/vcs/{org_id}/connections] GetV1VcsOrgIDConnections", response, response.Code())
	}
}

// NewGetV1VcsOrgIDConnectionsOK creates a GetV1VcsOrgIDConnectionsOK with default headers values
func NewGetV1VcsOrgIDConnectionsOK() *GetV1VcsOrgIDConnectionsOK {
	return &GetV1VcsOrgIDConnectionsOK{}
}

/*
GetV1VcsOrgIDConnectionsOK describes a response with status code 200, with default header values.

OK
*/
type GetV1VcsOrgIDConnectionsOK struct {
	Payload []*models.AppVCSConnection
}

// IsSuccess returns true when this get v1 vcs org Id connections o k response has a 2xx status code
func (o *GetV1VcsOrgIDConnectionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 vcs org Id connections o k response has a 3xx status code
func (o *GetV1VcsOrgIDConnectionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 vcs org Id connections o k response has a 4xx status code
func (o *GetV1VcsOrgIDConnectionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 vcs org Id connections o k response has a 5xx status code
func (o *GetV1VcsOrgIDConnectionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 vcs org Id connections o k response a status code equal to that given
func (o *GetV1VcsOrgIDConnectionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 vcs org Id connections o k response
func (o *GetV1VcsOrgIDConnectionsOK) Code() int {
	return 200
}

func (o *GetV1VcsOrgIDConnectionsOK) Error() string {
	return fmt.Sprintf("[GET /v1/vcs/{org_id}/connections][%d] getV1VcsOrgIdConnectionsOK  %+v", 200, o.Payload)
}

func (o *GetV1VcsOrgIDConnectionsOK) String() string {
	return fmt.Sprintf("[GET /v1/vcs/{org_id}/connections][%d] getV1VcsOrgIdConnectionsOK  %+v", 200, o.Payload)
}

func (o *GetV1VcsOrgIDConnectionsOK) GetPayload() []*models.AppVCSConnection {
	return o.Payload
}

func (o *GetV1VcsOrgIDConnectionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
