// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1VcsOrgIDConnectionsParams creates a new GetV1VcsOrgIDConnectionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1VcsOrgIDConnectionsParams() *GetV1VcsOrgIDConnectionsParams {
	return &GetV1VcsOrgIDConnectionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1VcsOrgIDConnectionsParamsWithTimeout creates a new GetV1VcsOrgIDConnectionsParams object
// with the ability to set a timeout on a request.
func NewGetV1VcsOrgIDConnectionsParamsWithTimeout(timeout time.Duration) *GetV1VcsOrgIDConnectionsParams {
	return &GetV1VcsOrgIDConnectionsParams{
		timeout: timeout,
	}
}

// NewGetV1VcsOrgIDConnectionsParamsWithContext creates a new GetV1VcsOrgIDConnectionsParams object
// with the ability to set a context for a request.
func NewGetV1VcsOrgIDConnectionsParamsWithContext(ctx context.Context) *GetV1VcsOrgIDConnectionsParams {
	return &GetV1VcsOrgIDConnectionsParams{
		Context: ctx,
	}
}

// NewGetV1VcsOrgIDConnectionsParamsWithHTTPClient creates a new GetV1VcsOrgIDConnectionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1VcsOrgIDConnectionsParamsWithHTTPClient(client *http.Client) *GetV1VcsOrgIDConnectionsParams {
	return &GetV1VcsOrgIDConnectionsParams{
		HTTPClient: client,
	}
}

/*
GetV1VcsOrgIDConnectionsParams contains all the parameters to send to the API endpoint

	for the get v1 vcs org ID connections operation.

	Typically these are written to a http.Request.
*/
type GetV1VcsOrgIDConnectionsParams struct {

	/* OrgID.

	   org ID for your current org
	*/
	OrgID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 vcs org ID connections params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1VcsOrgIDConnectionsParams) WithDefaults() *GetV1VcsOrgIDConnectionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 vcs org ID connections params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1VcsOrgIDConnectionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 vcs org ID connections params
func (o *GetV1VcsOrgIDConnectionsParams) WithTimeout(timeout time.Duration) *GetV1VcsOrgIDConnectionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 vcs org ID connections params
func (o *GetV1VcsOrgIDConnectionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 vcs org ID connections params
func (o *GetV1VcsOrgIDConnectionsParams) WithContext(ctx context.Context) *GetV1VcsOrgIDConnectionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 vcs org ID connections params
func (o *GetV1VcsOrgIDConnectionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 vcs org ID connections params
func (o *GetV1VcsOrgIDConnectionsParams) WithHTTPClient(client *http.Client) *GetV1VcsOrgIDConnectionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 vcs org ID connections params
func (o *GetV1VcsOrgIDConnectionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgID adds the orgID to the get v1 vcs org ID connections params
func (o *GetV1VcsOrgIDConnectionsParams) WithOrgID(orgID string) *GetV1VcsOrgIDConnectionsParams {
	o.SetOrgID(orgID)
	return o
}

// SetOrgID adds the orgId to the get v1 vcs org ID connections params
func (o *GetV1VcsOrgIDConnectionsParams) SetOrgID(orgID string) {
	o.OrgID = orgID
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1VcsOrgIDConnectionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param org_id
	if err := r.SetPathParam("org_id", o.OrgID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
