// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/terraform-provider-nuon/internal/api/client/models"
)

// GetV1VcsOrgIDConnectedReposReader is a Reader for the GetV1VcsOrgIDConnectedRepos structure.
type GetV1VcsOrgIDConnectedReposReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1VcsOrgIDConnectedReposReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1VcsOrgIDConnectedReposOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/vcs/{org_id}/connected-repos] GetV1VcsOrgIDConnectedRepos", response, response.Code())
	}
}

// NewGetV1VcsOrgIDConnectedReposOK creates a GetV1VcsOrgIDConnectedReposOK with default headers values
func NewGetV1VcsOrgIDConnectedReposOK() *GetV1VcsOrgIDConnectedReposOK {
	return &GetV1VcsOrgIDConnectedReposOK{}
}

/*
GetV1VcsOrgIDConnectedReposOK describes a response with status code 200, with default header values.

OK
*/
type GetV1VcsOrgIDConnectedReposOK struct {
	Payload []*models.ServiceRepository
}

// IsSuccess returns true when this get v1 vcs org Id connected repos o k response has a 2xx status code
func (o *GetV1VcsOrgIDConnectedReposOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 vcs org Id connected repos o k response has a 3xx status code
func (o *GetV1VcsOrgIDConnectedReposOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 vcs org Id connected repos o k response has a 4xx status code
func (o *GetV1VcsOrgIDConnectedReposOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 vcs org Id connected repos o k response has a 5xx status code
func (o *GetV1VcsOrgIDConnectedReposOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 vcs org Id connected repos o k response a status code equal to that given
func (o *GetV1VcsOrgIDConnectedReposOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 vcs org Id connected repos o k response
func (o *GetV1VcsOrgIDConnectedReposOK) Code() int {
	return 200
}

func (o *GetV1VcsOrgIDConnectedReposOK) Error() string {
	return fmt.Sprintf("[GET /v1/vcs/{org_id}/connected-repos][%d] getV1VcsOrgIdConnectedReposOK  %+v", 200, o.Payload)
}

func (o *GetV1VcsOrgIDConnectedReposOK) String() string {
	return fmt.Sprintf("[GET /v1/vcs/{org_id}/connected-repos][%d] getV1VcsOrgIdConnectedReposOK  %+v", 200, o.Payload)
}

func (o *GetV1VcsOrgIDConnectedReposOK) GetPayload() []*models.ServiceRepository {
	return o.Payload
}

func (o *GetV1VcsOrgIDConnectedReposOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
