// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/terraform-provider-nuon/internal/api/client/models"
)

// PatchV1OrgsOrgIDReader is a Reader for the PatchV1OrgsOrgID structure.
type PatchV1OrgsOrgIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchV1OrgsOrgIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchV1OrgsOrgIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/orgs/{org_id}] PatchV1OrgsOrgID", response, response.Code())
	}
}

// NewPatchV1OrgsOrgIDOK creates a PatchV1OrgsOrgIDOK with default headers values
func NewPatchV1OrgsOrgIDOK() *PatchV1OrgsOrgIDOK {
	return &PatchV1OrgsOrgIDOK{}
}

/*
PatchV1OrgsOrgIDOK describes a response with status code 200, with default header values.

OK
*/
type PatchV1OrgsOrgIDOK struct {
	Payload *models.AppOrg
}

// IsSuccess returns true when this patch v1 orgs org Id o k response has a 2xx status code
func (o *PatchV1OrgsOrgIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch v1 orgs org Id o k response has a 3xx status code
func (o *PatchV1OrgsOrgIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch v1 orgs org Id o k response has a 4xx status code
func (o *PatchV1OrgsOrgIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch v1 orgs org Id o k response has a 5xx status code
func (o *PatchV1OrgsOrgIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch v1 orgs org Id o k response a status code equal to that given
func (o *PatchV1OrgsOrgIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch v1 orgs org Id o k response
func (o *PatchV1OrgsOrgIDOK) Code() int {
	return 200
}

func (o *PatchV1OrgsOrgIDOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/orgs/{org_id}][%d] patchV1OrgsOrgIdOK  %+v", 200, o.Payload)
}

func (o *PatchV1OrgsOrgIDOK) String() string {
	return fmt.Sprintf("[PATCH /v1/orgs/{org_id}][%d] patchV1OrgsOrgIdOK  %+v", 200, o.Payload)
}

func (o *PatchV1OrgsOrgIDOK) GetPayload() *models.AppOrg {
	return o.Payload
}

func (o *PatchV1OrgsOrgIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppOrg)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
