// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/terraform-provider-nuon/internal/api/client/models"
)

// NewPatchV1OrgsOrgIDParams creates a new PatchV1OrgsOrgIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchV1OrgsOrgIDParams() *PatchV1OrgsOrgIDParams {
	return &PatchV1OrgsOrgIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchV1OrgsOrgIDParamsWithTimeout creates a new PatchV1OrgsOrgIDParams object
// with the ability to set a timeout on a request.
func NewPatchV1OrgsOrgIDParamsWithTimeout(timeout time.Duration) *PatchV1OrgsOrgIDParams {
	return &PatchV1OrgsOrgIDParams{
		timeout: timeout,
	}
}

// NewPatchV1OrgsOrgIDParamsWithContext creates a new PatchV1OrgsOrgIDParams object
// with the ability to set a context for a request.
func NewPatchV1OrgsOrgIDParamsWithContext(ctx context.Context) *PatchV1OrgsOrgIDParams {
	return &PatchV1OrgsOrgIDParams{
		Context: ctx,
	}
}

// NewPatchV1OrgsOrgIDParamsWithHTTPClient creates a new PatchV1OrgsOrgIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchV1OrgsOrgIDParamsWithHTTPClient(client *http.Client) *PatchV1OrgsOrgIDParams {
	return &PatchV1OrgsOrgIDParams{
		HTTPClient: client,
	}
}

/*
PatchV1OrgsOrgIDParams contains all the parameters to send to the API endpoint

	for the patch v1 orgs org ID operation.

	Typically these are written to a http.Request.
*/
type PatchV1OrgsOrgIDParams struct {

	/* OrgID.

	   org ID for your current org
	*/
	OrgID string

	/* Req.

	   Input
	*/
	Req *models.ServiceUpdateOrgRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch v1 orgs org ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1OrgsOrgIDParams) WithDefaults() *PatchV1OrgsOrgIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch v1 orgs org ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1OrgsOrgIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch v1 orgs org ID params
func (o *PatchV1OrgsOrgIDParams) WithTimeout(timeout time.Duration) *PatchV1OrgsOrgIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch v1 orgs org ID params
func (o *PatchV1OrgsOrgIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch v1 orgs org ID params
func (o *PatchV1OrgsOrgIDParams) WithContext(ctx context.Context) *PatchV1OrgsOrgIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch v1 orgs org ID params
func (o *PatchV1OrgsOrgIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch v1 orgs org ID params
func (o *PatchV1OrgsOrgIDParams) WithHTTPClient(client *http.Client) *PatchV1OrgsOrgIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch v1 orgs org ID params
func (o *PatchV1OrgsOrgIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgID adds the orgID to the patch v1 orgs org ID params
func (o *PatchV1OrgsOrgIDParams) WithOrgID(orgID string) *PatchV1OrgsOrgIDParams {
	o.SetOrgID(orgID)
	return o
}

// SetOrgID adds the orgId to the patch v1 orgs org ID params
func (o *PatchV1OrgsOrgIDParams) SetOrgID(orgID string) {
	o.OrgID = orgID
}

// WithReq adds the req to the patch v1 orgs org ID params
func (o *PatchV1OrgsOrgIDParams) WithReq(req *models.ServiceUpdateOrgRequest) *PatchV1OrgsOrgIDParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the patch v1 orgs org ID params
func (o *PatchV1OrgsOrgIDParams) SetReq(req *models.ServiceUpdateOrgRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *PatchV1OrgsOrgIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param org_id
	if err := r.SetPathParam("org_id", o.OrgID); err != nil {
		return err
	}
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
