// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/terraform-provider-nuon/internal/api/client/models"
)

// NewPatchV1AppsAppIDSandboxParams creates a new PatchV1AppsAppIDSandboxParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchV1AppsAppIDSandboxParams() *PatchV1AppsAppIDSandboxParams {
	return &PatchV1AppsAppIDSandboxParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchV1AppsAppIDSandboxParamsWithTimeout creates a new PatchV1AppsAppIDSandboxParams object
// with the ability to set a timeout on a request.
func NewPatchV1AppsAppIDSandboxParamsWithTimeout(timeout time.Duration) *PatchV1AppsAppIDSandboxParams {
	return &PatchV1AppsAppIDSandboxParams{
		timeout: timeout,
	}
}

// NewPatchV1AppsAppIDSandboxParamsWithContext creates a new PatchV1AppsAppIDSandboxParams object
// with the ability to set a context for a request.
func NewPatchV1AppsAppIDSandboxParamsWithContext(ctx context.Context) *PatchV1AppsAppIDSandboxParams {
	return &PatchV1AppsAppIDSandboxParams{
		Context: ctx,
	}
}

// NewPatchV1AppsAppIDSandboxParamsWithHTTPClient creates a new PatchV1AppsAppIDSandboxParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchV1AppsAppIDSandboxParamsWithHTTPClient(client *http.Client) *PatchV1AppsAppIDSandboxParams {
	return &PatchV1AppsAppIDSandboxParams{
		HTTPClient: client,
	}
}

/*
PatchV1AppsAppIDSandboxParams contains all the parameters to send to the API endpoint

	for the patch v1 apps app ID sandbox operation.

	Typically these are written to a http.Request.
*/
type PatchV1AppsAppIDSandboxParams struct {

	/* AppID.

	   app ID
	*/
	AppID string

	/* Req.

	   Input
	*/
	Req *models.ServiceUpdateAppSandboxRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch v1 apps app ID sandbox params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1AppsAppIDSandboxParams) WithDefaults() *PatchV1AppsAppIDSandboxParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch v1 apps app ID sandbox params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1AppsAppIDSandboxParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch v1 apps app ID sandbox params
func (o *PatchV1AppsAppIDSandboxParams) WithTimeout(timeout time.Duration) *PatchV1AppsAppIDSandboxParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch v1 apps app ID sandbox params
func (o *PatchV1AppsAppIDSandboxParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch v1 apps app ID sandbox params
func (o *PatchV1AppsAppIDSandboxParams) WithContext(ctx context.Context) *PatchV1AppsAppIDSandboxParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch v1 apps app ID sandbox params
func (o *PatchV1AppsAppIDSandboxParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch v1 apps app ID sandbox params
func (o *PatchV1AppsAppIDSandboxParams) WithHTTPClient(client *http.Client) *PatchV1AppsAppIDSandboxParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch v1 apps app ID sandbox params
func (o *PatchV1AppsAppIDSandboxParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the patch v1 apps app ID sandbox params
func (o *PatchV1AppsAppIDSandboxParams) WithAppID(appID string) *PatchV1AppsAppIDSandboxParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the patch v1 apps app ID sandbox params
func (o *PatchV1AppsAppIDSandboxParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithReq adds the req to the patch v1 apps app ID sandbox params
func (o *PatchV1AppsAppIDSandboxParams) WithReq(req *models.ServiceUpdateAppSandboxRequest) *PatchV1AppsAppIDSandboxParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the patch v1 apps app ID sandbox params
func (o *PatchV1AppsAppIDSandboxParams) SetReq(req *models.ServiceUpdateAppSandboxRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *PatchV1AppsAppIDSandboxParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_id
	if err := r.SetPathParam("app_id", o.AppID); err != nil {
		return err
	}
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
