// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/terraform-provider-nuon/internal/api/client/models"
)

// NewPostV1VcsOrgIDConnectionParams creates a new PostV1VcsOrgIDConnectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1VcsOrgIDConnectionParams() *PostV1VcsOrgIDConnectionParams {
	return &PostV1VcsOrgIDConnectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1VcsOrgIDConnectionParamsWithTimeout creates a new PostV1VcsOrgIDConnectionParams object
// with the ability to set a timeout on a request.
func NewPostV1VcsOrgIDConnectionParamsWithTimeout(timeout time.Duration) *PostV1VcsOrgIDConnectionParams {
	return &PostV1VcsOrgIDConnectionParams{
		timeout: timeout,
	}
}

// NewPostV1VcsOrgIDConnectionParamsWithContext creates a new PostV1VcsOrgIDConnectionParams object
// with the ability to set a context for a request.
func NewPostV1VcsOrgIDConnectionParamsWithContext(ctx context.Context) *PostV1VcsOrgIDConnectionParams {
	return &PostV1VcsOrgIDConnectionParams{
		Context: ctx,
	}
}

// NewPostV1VcsOrgIDConnectionParamsWithHTTPClient creates a new PostV1VcsOrgIDConnectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1VcsOrgIDConnectionParamsWithHTTPClient(client *http.Client) *PostV1VcsOrgIDConnectionParams {
	return &PostV1VcsOrgIDConnectionParams{
		HTTPClient: client,
	}
}

/*
PostV1VcsOrgIDConnectionParams contains all the parameters to send to the API endpoint

	for the post v1 vcs org ID connection operation.

	Typically these are written to a http.Request.
*/
type PostV1VcsOrgIDConnectionParams struct {

	/* OrgID.

	   org ID for your current org
	*/
	OrgID string

	/* Req.

	   Input
	*/
	Req *models.ServiceCreateOrgConnectionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 vcs org ID connection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1VcsOrgIDConnectionParams) WithDefaults() *PostV1VcsOrgIDConnectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 vcs org ID connection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1VcsOrgIDConnectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 vcs org ID connection params
func (o *PostV1VcsOrgIDConnectionParams) WithTimeout(timeout time.Duration) *PostV1VcsOrgIDConnectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 vcs org ID connection params
func (o *PostV1VcsOrgIDConnectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 vcs org ID connection params
func (o *PostV1VcsOrgIDConnectionParams) WithContext(ctx context.Context) *PostV1VcsOrgIDConnectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 vcs org ID connection params
func (o *PostV1VcsOrgIDConnectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 vcs org ID connection params
func (o *PostV1VcsOrgIDConnectionParams) WithHTTPClient(client *http.Client) *PostV1VcsOrgIDConnectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 vcs org ID connection params
func (o *PostV1VcsOrgIDConnectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgID adds the orgID to the post v1 vcs org ID connection params
func (o *PostV1VcsOrgIDConnectionParams) WithOrgID(orgID string) *PostV1VcsOrgIDConnectionParams {
	o.SetOrgID(orgID)
	return o
}

// SetOrgID adds the orgId to the post v1 vcs org ID connection params
func (o *PostV1VcsOrgIDConnectionParams) SetOrgID(orgID string) {
	o.OrgID = orgID
}

// WithReq adds the req to the post v1 vcs org ID connection params
func (o *PostV1VcsOrgIDConnectionParams) WithReq(req *models.ServiceCreateOrgConnectionRequest) *PostV1VcsOrgIDConnectionParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the post v1 vcs org ID connection params
func (o *PostV1VcsOrgIDConnectionParams) SetReq(req *models.ServiceCreateOrgConnectionRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1VcsOrgIDConnectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param org_id
	if err := r.SetPathParam("org_id", o.OrgID); err != nil {
		return err
	}
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
