// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/terraform-provider-nuon/internal/api/client/models"
)

// PostV1OrgsOrgIDUserReader is a Reader for the PostV1OrgsOrgIDUser structure.
type PostV1OrgsOrgIDUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1OrgsOrgIDUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostV1OrgsOrgIDUserCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/orgs/{org_id}/user] PostV1OrgsOrgIDUser", response, response.Code())
	}
}

// NewPostV1OrgsOrgIDUserCreated creates a PostV1OrgsOrgIDUserCreated with default headers values
func NewPostV1OrgsOrgIDUserCreated() *PostV1OrgsOrgIDUserCreated {
	return &PostV1OrgsOrgIDUserCreated{}
}

/*
PostV1OrgsOrgIDUserCreated describes a response with status code 201, with default header values.

Created
*/
type PostV1OrgsOrgIDUserCreated struct {
	Payload *models.AppUserOrg
}

// IsSuccess returns true when this post v1 orgs org Id user created response has a 2xx status code
func (o *PostV1OrgsOrgIDUserCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 orgs org Id user created response has a 3xx status code
func (o *PostV1OrgsOrgIDUserCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 orgs org Id user created response has a 4xx status code
func (o *PostV1OrgsOrgIDUserCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 orgs org Id user created response has a 5xx status code
func (o *PostV1OrgsOrgIDUserCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 orgs org Id user created response a status code equal to that given
func (o *PostV1OrgsOrgIDUserCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post v1 orgs org Id user created response
func (o *PostV1OrgsOrgIDUserCreated) Code() int {
	return 201
}

func (o *PostV1OrgsOrgIDUserCreated) Error() string {
	return fmt.Sprintf("[POST /v1/orgs/{org_id}/user][%d] postV1OrgsOrgIdUserCreated  %+v", 201, o.Payload)
}

func (o *PostV1OrgsOrgIDUserCreated) String() string {
	return fmt.Sprintf("[POST /v1/orgs/{org_id}/user][%d] postV1OrgsOrgIdUserCreated  %+v", 201, o.Payload)
}

func (o *PostV1OrgsOrgIDUserCreated) GetPayload() *models.AppUserOrg {
	return o.Payload
}

func (o *PostV1OrgsOrgIDUserCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppUserOrg)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
