// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/terraform-provider-nuon/internal/api/client/models"
)

// PostV1VcsOrgIDConnectionReader is a Reader for the PostV1VcsOrgIDConnection structure.
type PostV1VcsOrgIDConnectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1VcsOrgIDConnectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostV1VcsOrgIDConnectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/vcs/{org_id}/connection] PostV1VcsOrgIDConnection", response, response.Code())
	}
}

// NewPostV1VcsOrgIDConnectionOK creates a PostV1VcsOrgIDConnectionOK with default headers values
func NewPostV1VcsOrgIDConnectionOK() *PostV1VcsOrgIDConnectionOK {
	return &PostV1VcsOrgIDConnectionOK{}
}

/*
PostV1VcsOrgIDConnectionOK describes a response with status code 200, with default header values.

OK
*/
type PostV1VcsOrgIDConnectionOK struct {
	Payload *models.AppVCSConnection
}

// IsSuccess returns true when this post v1 vcs org Id connection o k response has a 2xx status code
func (o *PostV1VcsOrgIDConnectionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 vcs org Id connection o k response has a 3xx status code
func (o *PostV1VcsOrgIDConnectionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 vcs org Id connection o k response has a 4xx status code
func (o *PostV1VcsOrgIDConnectionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 vcs org Id connection o k response has a 5xx status code
func (o *PostV1VcsOrgIDConnectionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 vcs org Id connection o k response a status code equal to that given
func (o *PostV1VcsOrgIDConnectionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post v1 vcs org Id connection o k response
func (o *PostV1VcsOrgIDConnectionOK) Code() int {
	return 200
}

func (o *PostV1VcsOrgIDConnectionOK) Error() string {
	return fmt.Sprintf("[POST /v1/vcs/{org_id}/connection][%d] postV1VcsOrgIdConnectionOK  %+v", 200, o.Payload)
}

func (o *PostV1VcsOrgIDConnectionOK) String() string {
	return fmt.Sprintf("[POST /v1/vcs/{org_id}/connection][%d] postV1VcsOrgIdConnectionOK  %+v", 200, o.Payload)
}

func (o *PostV1VcsOrgIDConnectionOK) GetPayload() *models.AppVCSConnection {
	return o.Payload
}

func (o *PostV1VcsOrgIDConnectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppVCSConnection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
