// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/terraform-provider-nuon/internal/api/client/models"
)

// NewPostV1OrgsOrgIDUserParams creates a new PostV1OrgsOrgIDUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1OrgsOrgIDUserParams() *PostV1OrgsOrgIDUserParams {
	return &PostV1OrgsOrgIDUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1OrgsOrgIDUserParamsWithTimeout creates a new PostV1OrgsOrgIDUserParams object
// with the ability to set a timeout on a request.
func NewPostV1OrgsOrgIDUserParamsWithTimeout(timeout time.Duration) *PostV1OrgsOrgIDUserParams {
	return &PostV1OrgsOrgIDUserParams{
		timeout: timeout,
	}
}

// NewPostV1OrgsOrgIDUserParamsWithContext creates a new PostV1OrgsOrgIDUserParams object
// with the ability to set a context for a request.
func NewPostV1OrgsOrgIDUserParamsWithContext(ctx context.Context) *PostV1OrgsOrgIDUserParams {
	return &PostV1OrgsOrgIDUserParams{
		Context: ctx,
	}
}

// NewPostV1OrgsOrgIDUserParamsWithHTTPClient creates a new PostV1OrgsOrgIDUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1OrgsOrgIDUserParamsWithHTTPClient(client *http.Client) *PostV1OrgsOrgIDUserParams {
	return &PostV1OrgsOrgIDUserParams{
		HTTPClient: client,
	}
}

/*
PostV1OrgsOrgIDUserParams contains all the parameters to send to the API endpoint

	for the post v1 orgs org ID user operation.

	Typically these are written to a http.Request.
*/
type PostV1OrgsOrgIDUserParams struct {

	/* OrgID.

	   org ID for your current org
	*/
	OrgID string

	/* Req.

	   Input
	*/
	Req *models.ServiceCreateOrgUserRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 orgs org ID user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1OrgsOrgIDUserParams) WithDefaults() *PostV1OrgsOrgIDUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 orgs org ID user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1OrgsOrgIDUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 orgs org ID user params
func (o *PostV1OrgsOrgIDUserParams) WithTimeout(timeout time.Duration) *PostV1OrgsOrgIDUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 orgs org ID user params
func (o *PostV1OrgsOrgIDUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 orgs org ID user params
func (o *PostV1OrgsOrgIDUserParams) WithContext(ctx context.Context) *PostV1OrgsOrgIDUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 orgs org ID user params
func (o *PostV1OrgsOrgIDUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 orgs org ID user params
func (o *PostV1OrgsOrgIDUserParams) WithHTTPClient(client *http.Client) *PostV1OrgsOrgIDUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 orgs org ID user params
func (o *PostV1OrgsOrgIDUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgID adds the orgID to the post v1 orgs org ID user params
func (o *PostV1OrgsOrgIDUserParams) WithOrgID(orgID string) *PostV1OrgsOrgIDUserParams {
	o.SetOrgID(orgID)
	return o
}

// SetOrgID adds the orgId to the post v1 orgs org ID user params
func (o *PostV1OrgsOrgIDUserParams) SetOrgID(orgID string) {
	o.OrgID = orgID
}

// WithReq adds the req to the post v1 orgs org ID user params
func (o *PostV1OrgsOrgIDUserParams) WithReq(req *models.ServiceCreateOrgUserRequest) *PostV1OrgsOrgIDUserParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the post v1 orgs org ID user params
func (o *PostV1OrgsOrgIDUserParams) SetReq(req *models.ServiceCreateOrgUserRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1OrgsOrgIDUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param org_id
	if err := r.SetPathParam("org_id", o.OrgID); err != nil {
		return err
	}
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
